### ISSUE TITLE
Fabric's chunk loading event does not seem to be invoked

### ISSUE THREAD

**Issue by dima-dencep** [Tuinity/Moonrise#16]
https://github.com/FabricMC/fabric/blob/1.21.1/fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ChunkGeneratingMixin.java#L37

**Comment by dima-dencep** [comment]
And at least one event is not invoked on neoforge: https://github.com/neoforged/NeoForge/blob/1.21.x/src/main/java/net/neoforged/neoforge/event/entity/EntityEvent.java#L63

**Comment by jpenilla** [comment]
> And at least one event is not invoked on neoforge: https://github.com/neoforged/NeoForge/blob/1.21.x/src/main/java/net/neoforged/neoforge/event/entity/EntityEvent.java#L63

https://github.com/Tuinity/Moonrise/blob/d1f8e8191352de009e760dcbd9e31c456f568ed6/neoforge/src/main/java/ca/spottedleaf/moonrise/neoforge/NeoForgeHooks.java#L149

**Comment by dima-dencep** [comment]
Well, it's just that I have this event ported to the fabric, so I thought it wasn't working
