### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by kitovoi111** [Tuinity/Moonrise#20]
mods 
![image](https://github.com/user-attachments/assets/a803655d-49b1-4d99-94e2-3062dd93c89a)
logs
[crash-2024-09-11_16.50.18-server.txt](https://github.com/user-attachments/files/16964534/crash-2024-09-11_16.50.18-server.txt)
[latest.log](https://github.com/user-attachments/files/16964536/latest.log)

**Comment by kitovoi111** [comment]
[crash-2024-09-11_16.51.11-server.txt](https://github.com/user-attachments/files/16964555/crash-2024-09-11_16.51.11-server.txt)

**Comment by jpenilla** [comment]
Please open individual issues for each conflicting mod, including details such as the mod loader, versions, crash reports, logs, etc. Unfocused issues like this make things very difficult to take action on.
