### ISSUE TITLE
Moonrise incompatible with puzzleslib and creativecore

### ISSUE THREAD

**Issue by vroooooooooo** [Tuinity/Moonrise#21]
logs
https://mclo.gs/5nqCH1A

**Comment by 456dev** [comment]
creative core issue is known https://github.com/CreativeMD/CreativeCore/issues/255 where it seems the author isnt looking into it at the moment

**Comment by jpenilla** [comment]
https://github.com/Tuinity/Moonrise/commit/0958439e54e524ecac30238d53bb20fc308f121a CreativeCore issue is resolved in the latest action artifact, this change will be included in the next beta.

Please open individual issues for each mod incompatibility, including logs and crash reports if relevant, and the platform (NeoForge/Fabric/Both) where the conflict takes place, as well as any other context needed to describe the issue and to reproduce it.
