### ISSUE TITLE
[Incompatibility] moonrise's collision optimization with some mods

### ISSUE THREAD

**Issue by Rozbiynk** [Tuinity/Moonrise#30]
https://mclo.gs/atDqqso
list of mods
![изображение](https://github.com/user-attachments/assets/fdbe3ef5-0739-4ae3-9ae2-0226a100f31e)

**Comment by Rozbiynk** [comment]
after disabling mixin that was printed in crash log it show me another error, now about explosions https://mclo.gs/ghnAdXu

**Comment by Rozbiynk** [comment]
oh it also applies for collision, just another part of code from tis

**Comment by Rozbiynk** [comment]
according to #24 set "required" to false in carpet-tis-addition.mixins.json inside mod make it loads fine. Creative no clip and explosions both works fine

**Comment by Rozbiynk** [comment]
next is https://modrinth.com/mod/vanish https://mclo.gs/mwPBciy

**Comment by Rozbiynk** [comment]
also many of incompatibilities with https://github.com/Tater-Certified/Potatoptimize, i can provide list of mixins later (but he can be disabled in config)

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/46e070522b20db2896e56876de026c0d

Been getting a crash with ferritecore on 1.21.1 neforge

**Comment by jpenilla** [comment]
@BugmanBugman the needed config changes for FC are in the readme

**Comment by jpenilla** [comment]
Please open individual issues for each conflicting mod, including details such as the mod loader, versions, crash reports, logs, etc. Unfocused issues like this make things very difficult to take action on.
