### ISSUE TITLE
[Mod-incompat] [neo] Legacy 4J x Moonrise

### ISSUE THREAD

**Issue by Cixon** [Tuinity/Moonrise#39]
Hey friends! Just a minor mixin conflict. 🫡🚧

### Source for mixin conflict (i could be wrong):
https://github.com/Wilyicaro/Legacy-Minecraft/blob/1.21/common/src/main/java/wily/legacy/mixin/EntityMixin.java

**Line 55:**
[latest.log](https://github.com/user-attachments/files/17198996/latest.log)

No crash provided.

**Comment by Cixon** [comment]
### Additional Details:

**Legacy 4J:**
v1.7.4
`https://modrinth.com/mod/legacy4j/version/1.21-1.7.4+neoforge`

**Moonrise:**
Moonrise-NeoForge-0.1.0-beta.4+e244c60

**NeoForge:**
21.1.59

**Comment by jpenilla** [comment]
I'm not sure if we can fix this on our end without clobbering their changes given we rewrite the entire method.

If they were to `@WrapOperation` on the single call to the collide method in `Entity#move` and temporarily modify the `onGround` field it could be resolved on their end.

Something like the following (pseudocode):
```java
@Shadow
private boolean onGround;

@WrapOperation(method = "move", at = @At(value = "INVOKE", target = "collide"))
private Vec3 wrapCollide(Entity instance, Vec3 param, Operation<Vec3> original) {
    if (!(instance instanceof Player player)) {
        return original.call(instance, param);
    }
    final boolean prev = ((EntityMixin) instance).onGround;
    try {
        ((EntityMixin) instance).onGround = ((EntityMixin) instance).onGround || p.getAbilities().flying;
        return original.call(instance, param);
    } finally {
        ((EntityMixin) instance).onGround = prev;
    }
}
```

**Comment by Cixon** [comment]
I'll mention this ticket over to them for now, thanks for the info!
