### ISSUE TITLE
Crash due to Entity Movement Tracking in Moonrise Mod

### ISSUE THREAD

**Issue by gjeempe** [Tuinity/Moonrise#42]
I experienced server crashes while using the Moonrise mod alongside Lithium on Minecraft 1.21.1. The crashes occurred with a "Ticking block entity" error related to Lithium's entity movement tracking, specifically:

java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.lithium.mixin.util.entity_movement_tracking.ServerEntityManagerAccessor.getCache()"

Removing the Moonrise mod resolved the crashe

Steps to Reproduce:

1. Install Moonrise and Lithium mods.
2. Start the server and allow players to join.
3. Put a sink into the chest to activate entity movement.
4. Observe crashes when players interact with block entities, indicating a compatibility issue.

Minecraft Version: 1.21.1
Moonrise Version: Moonrise-NeoForge 0.1.0-beta.4+e244c60
Lithium Version: lithium 0.13.1
Other Mods: [I can provide if needed, but looks like it's moonrise <> lithium related problem]

PC: Ubuntu Server on Acer Aspire X3900 with i5-750/16GB DDR3/512SSD
Game Server: fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar

**Comment by gjeempe** [comment]
> Lithium will not be compatible on NeoForge until there are official builds of Lithium available for the platform. Use Radium for now.

I'm sorry but I copy/pasted wrong version of Moonrise.
I'm using: **Moonrise-Fabric 0.1.0-beta.4+e244c60** 
on: **fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1**
I can share a copy of my server with admin/infrastructure etc (as I'm hosting those online as hobby-non-profit) if needed. 
Thanks for understanding.

**Comment by jpenilla** [comment]
In that case, are you 100% sure that you are using beta 4 and not beta 3? This sounds awfully like an issue that was fixed in beta 4, and I can't reproduce any problems with Hoppers pointing into chests. Please share the full log through https://mclo.gs/ or a Gist.

**Comment by gjeempe** [comment]
> In that case, are you 100% sure that you are using beta 4 and not beta 3? This sounds awfully like an issue that was fixed in beta 4, and I can't reproduce any problems with Hoppers pointing into chests. Please share the full log through https://mclo.gs/ or a Gist.

Yes I was wrong second time. Sorry for taking your precious time. I was using Moonrise-Fabric-0.1.0-beta.3+23eddfe.jar as I'm looking now. Beta4 was on the different server that I'm hosting. 
Will report issues next time with more check';s from my side. Thank you.
