### ISSUE TITLE
[Inquiry] Is this mod ideal to run with Krypton Foxified?

### ISSUE THREAD

**Issue by Cixon** [Tuinity/Moonrise#43]
### Mod

https://modrinth.com/mod/krypton-foxified

Just genuinely curious if running Moonrise with Krypton would be beneficial or perhaps hinder me. I also am curious if it’ll bottleneck server performance? I’m not too tech savvy. Thanks!

**Comment by jpenilla** [comment]
In theory, they should work fine together. Both mods are implemented in Paper.

In the future please prefer GitHub discussions or the Discord for these types of questions.
