### ISSUE TITLE
Entities Prevented from Removal Due to Section Status Updates

### ISSUE THREAD

**Issue by gjeempe** [Tuinity/Moonrise#44]
**Description:** When running a Minecraft server, certain entities are being prevented from being removed with the following warning message:
```
[Server thread/WARN]: Entity class_1642['Zombie'/13764, l='ServerLevel[L4V4 W0RLD]', x=103.50, y=-10.00, z=40.50] is currently prevented from being removed from the world since it is processing section status updates
java.lang.Throwable: null
```
The server experiences a spam of such warnings, particularly during times of high entity activity, causing performance issues and excessive logging.

Steps to Reproduce:
1. Allow multiple entities (Zombies, Skeletons, etc.) to spawn.
2. Monitor logs for the spam of warnings as entities attempt to be removed from the world.

Expected Behavior: Entities should be removed properly without generating excessive warnings or causing server performance issues.
Observed Behavior: Entities remain stuck in the world during section status updates, leading to repeated log warnings, increased CPU usage, and cluttered log files.

Versions (Include all relevant server mods/plugins):
Minecraft Version: Minecraft 1.21.1
Server Type: Fabric server 1.21.1 Fabric Loader 0.16.5 Launcher 1.0.1
Plugins: Listed in log file.
Log file: https://mclo.gs/kykwfzK

**Comment by jpenilla** [comment]
This issue is with the mod owning this code:
`at com.natamus.collective_common_fabric.events.CollectiveEvents.onEntityJoinLevel(CollectiveEvents.java:216) ~[collective-1.21.1-7.84.jar:?]`

Removing an entity during tracker updates is also an error and unsafe in Vanilla, the difference is that Vanilla does not proactively guard against these errors. In Vanilla this can result in memory leaks as the entity could still be added to the ticking list.

**Comment by gjeempe** [comment]
> This issue is with the mod owning this code: `at com.natamus.collective_common_fabric.events.CollectiveEvents.onEntityJoinLevel(CollectiveEvents.java:216) ~[collective-1.21.1-7.84.jar:?]`

Thanks for pointing me in the right direction regarding the entity removal issue. I’ve raised the issue with the Collective mod team based on your insights about tracker updates. For reference, the related issue can be found here: [Collective Issue #2682](https://github.com/Serilum/.issue-tracker/issues/2682).

Appreciate your help!
