### ISSUE TITLE
[Incompatibility] Crash Occurs when playing with Moonrise & GregTech

### ISSUE THREAD

**Issue by Azraeel** [Tuinity/Moonrise#46]
Crash occurs when generating new chunks, there is currently a conflict between Moonrise & GregTech that causes Servers to hard crash right now.
NeoForge 1.21.1

**Comment by Skullians** [comment]
Logs?

**Comment by jpenilla** [comment]
Please open a new issue with the template properly filled out (i.e. including crash reports, logs, versions, etc.)
