### ISSUE TITLE
[Incompatiblity] Servercore and Moonrise

### ISSUE THREAD

**Issue by JamesisFonny** [Tuinity/Moonrise#50]
Server crashed when using moonrise with server core

https://mclo.gs/CYUNroK

**Comment by jpenilla** [comment]
Please ensure both Moonrise and the suspected incompatible mod are up to date before reporting issues. In this case you are using outdated servercore.

**Comment by JamesisFonny** [comment]
I want my server to stay in 1.21, but the latest servercore shows it only support 1.21.1. So, I guess they can't be use together in 1.21?

**Comment by JamesisFonny** [comment]
at least add the incompability info to your mod description on modrinth
