### ISSUE TITLE
Backport Question.

### ISSUE THREAD

**Issue by Skullians** [Tuinity/Moonrise#6]
Yeah, this is kind of a ridiculous question.

What's the possibility of this being backported into older versions such as 1.20.x, 1.19.x?
I understand the insane complexity of this mod, however mc versions like 1.20.x and 1.19.x have many more content mods compared to 1.21.x, and would greatly benefit from this.

**Comment by jpenilla** [comment]
Moonrise will not be backported to older versions, someone else may backport it unofficially as long as they follow the license.

**Comment by Skullians** [comment]
Okay. Thanks for your time.
