### ISSUE TITLE
[Incompatibility: Fabric]: architectury, carpet, carpet tis addon, tweakeroo, viafabricplus, very many players & debugify

### ISSUE THREAD

**Issue by M1noa** [Tuinity/Moonrise#61]
### Minecraft Version

1.21

### Moonrise Version

Moonrise-Fabric-0.1.0-beta.7+8040c7a

### Mod Loader

Fabric

### Logs and Crash Reports

mixin trace stopped every crash, i put all mods into a folder and I got the list in the title

### Additional Context

i wish moonlight wasnt so incompatible, i got all of these before getting into a world.. i hope a starlight fork pops up eventually or these issues get fixed.

**Comment by jpenilla** [comment]
Fill out the issue template properly (i.e. including logs and traces unless there is a specific reason it's not relevant) for individual mod conflicts. Make sure to check for existing issues first.
