### ISSUE TITLE
[Incompatibility: NeoForge]: Minecolonies

### ISSUE THREAD

**Issue by Gaz492** [Tuinity/Moonrise#69]
### Minecraft Version

1.21.1

### Moonrise Version

0.1.0-beta.8+68ea18b

### Mod Loader

NeoForge

### Logs and Crash Reports

https://pste.me/@5PcytE9Oib8

### Additional Context

This happens when trying to reinstate a town hall in an abandoned colony.

1. Find abandoned settlement
2. Open the town hall
3. Click on Reinstate button
4. Click on sign and found colony button
5. Crash

Originally reported to the Minecolonies devs: https://github.com/ldtteam/minecolonies/issues/10417
[](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6109)

**Comment by satakrion** [comment]
can confirm. see: https://github.com/ldtteam/minecolonies/issues/10418

**Comment by jpenilla** [comment]
Fixed in https://github.com/ldtteam/minecolonies/pull/10422
