### ISSUE TITLE
[Incompatibility: Fabric]: Lithium and ViaFabricPlus together

### ISSUE THREAD

**Issue by EveningPrim** [Tuinity/Moonrise#74]
### Minecraft Version

1.21.3

### Moonrise Version

0.2.0-SNAPSHOT+1e39f53

### Mod Loader

Fabric

### Logs and Crash Reports

https://mclo.gs/kbkNXB7

### Additional Context

Crash on launch when Lithium and ViaFabricPlus are run together with Moonrise

**Comment by jpenilla** [comment]
This should be reported to ViaFabricPlus, it looks like they are failing to mixin to lithium as Moonrise disables the features they try to edit in favor of its own collision optimizations.

**Comment by jpenilla** [comment]
https://github.com/ViaVersion/ViaFabricPlus/issues/620

**Comment by florianreuth** [comment]
Fixed in ViaFabricPlus, this issue can be closed now.
